version: '3.8'

services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    restart: always
    networks:
    - python-network
    
  nodejs:
    build: .
    container_name: nodejs
    image: nodejs
    ports:
      - 3000:3000
    links:
      - mongodb
    networks:
    - python-network
    depends_on:
      - mongodb

# volumes:
#   dbdata:

networks:
  python-network:
    # driver: bridge